#!/usr/bin/env python3
"""
aricode-pack v0.1 — model → static binary compiler.

Given a PyTorch state_dict and an explicit architecture spec, emit:
    <out>.ari   aricode source for the forward pass
    <out>.f32   raw little-endian f32 weights blob (in arch order)

The `aric` compiler then turns <out>.ari into a static x86_64+AVX2
binary that loads <out>.f32 at startup and serves inference.  No
PyTorch, no Python, no CUDA — a few hundred KB total.

This v0.1 supports a deliberately small layer vocabulary: Linear,
ReLU, Sigmoid, Tanh, Softmax (output).  CNN + attention land in
v0.2 once the layer template family stabilises.

Architecture spec is a Python list of (kind, *args) tuples:

    ARCH = [
        ("linear", 784, 64),      # in_features, out_features
        ("relu",),
        ("linear", 64, 10),
        # The runtime adds an argmax over the final layer for
        # classification — opt out with `--no-argmax`.
    ]

Weight order in the blob matches the layer order: every Linear
emits W (out × in row-major) then b (out,) before the next layer's
weights.  state_dict keys are matched positionally — pass `--keys`
to override the default `fc{N}.weight / fc{N}.bias` pattern.

Usage:
    python aricode_pack.py \\
        --checkpoint trained.pt \\
        --arch arch.json \\
        --input-format mnist \\
        --input-images t10k-images-idx3-ubyte \\
        --input-labels t10k-labels-idx1-ubyte \\
        --n-test 10000 \\
        --out my_classifier

    aric my_classifier.ari -o my_classifier
    ./my_classifier
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import torch
except ImportError:
    torch = None  # only needed when reading .pt; fail late and clearly.


# ──────────────────────────────────────────────────────────────────────
#  Layer schema — every supported layer registers (i) the weight slots
#  it expects in the state_dict, (ii) how big a scratch buffer it
#  needs, (iii) the .ari snippet that runs its forward pass.
# ──────────────────────────────────────────────────────────────────────


def linear_weights(idx: int, in_f: int, out_f: int, sd, key_pattern: str):
    w_key = key_pattern.format(idx=idx, kind="weight")
    b_key = key_pattern.format(idx=idx, kind="bias")
    if w_key not in sd or b_key not in sd:
        raise KeyError(
            f"linear layer #{idx}: missing key '{w_key}' or '{b_key}' "
            f"in state_dict.  Pass --keys to customise."
        )
    W = sd[w_key].detach().cpu().numpy().astype("float32")
    b = sd[b_key].detach().cpu().numpy().astype("float32")
    if W.shape != (out_f, in_f) or b.shape != (out_f,):
        raise ValueError(
            f"linear #{idx}: shape mismatch.  expected W=({out_f},{in_f}) "
            f"b=({out_f},), got W={tuple(W.shape)} b={tuple(b.shape)}."
        )
    return [W, b]


def emit_linear(idx, in_f, out_f, src_var, dst_var, w_var, b_var):
    return [
        f"    arr_f32_matvec({w_var}, {src_var}, {b_var}, {dst_var}, {out_f}, {in_f});",
    ]


def emit_relu(var):
    return [f"    arr_f32_relu({var});"]


def emit_sigmoid(var):
    return [f"    arr_f32_sigmoid({var});"]   # f64 builtin; user must promote


def emit_tanh(var):
    return [f"    arr_f32_tanh({var});"]


def emit_softmax(var):
    return [f"    arr_f32_softmax({var});"]


# ──────────────────────────────────────────────────────────────────────
#  Code generator: walks the arch list and emits a self-contained
#  aricode source that loads the weight blob, runs the test loop, and
#  reports accuracy.
# ──────────────────────────────────────────────────────────────────────


PROLOGUE = """\
// Generated by aricode-pack v0.1 — DO NOT EDIT.
//
// model: {model_name}
// arch:  {arch_repr}
// loader: {loader}
// (run aricode_pack.py to regenerate after retraining.)

fn arr_f32_from_file_into(fd: i32, buf: i32, n: i32) -> i32 {{
    file_read(fd, buf, n * 4);
    return 0;
}}

fn load_byte_file(path_str: i32, byte_count: i32) -> i32 {{
    let slots: i32 = (byte_count + 7) / 8;
    let buf: i32 = arr_new(slots);
    let fd: i32 = file_open(path_str, 0);
    file_read(fd, buf, byte_count);
    file_close(fd);
    return buf;
}}

fn argmax_f32(buf: i32, n: i32) -> i32 {{
    let best_i: i32 = 0;
    let best_v: f64 = arr_f32_get(buf, 0);
    let i: i32 = 1;
    while (i < n) {{
        let v: f64 = arr_f32_get(buf, i);
        if (v > best_v) {{ best_v = v; best_i = i; }}
        i = i + 1;
    }}
    return best_i;
}}
"""


MNIST_LOADER = """\
fn load_image_at(img_buf: i32, offset: i32, out: i32) -> i32 {{
    let i: i32 = 0;
    while (i < {n_in}) {{
        let px: i32 = byte_at(img_buf, offset + i);
        // Standardised the same way as the trainer.
        arr_f32_set(out, i, (int_to_float(px) / 255.0 - {mean}) / {std});
        i = i + 1;
    }}
    return 0;
}}
"""


def linear_layers(arch):
    """Yield (idx, in_f, out_f) for every Linear in the arch order."""
    li = 0
    for kind, *args in arch:
        if kind == "linear":
            yield li, args[0], args[1]
            li += 1


def collect_weights(arch, sd, key_pattern):
    """Return a flat list of f32 numpy arrays, in load order."""
    out = []
    for idx, in_f, out_f in linear_layers(arch):
        out.extend(linear_weights(idx, in_f, out_f, sd, key_pattern))
    return out


def gen_weight_decls(arch, embed):
    """Either pre-allocated empty tensors (filled by file_read later) or
    nothing (embed_file inside gen_load declares the let bindings)."""
    if embed:
        return []
    lines = []
    for idx, in_f, out_f in linear_layers(arch):
        lines.append(f"    let W{idx}: i32 = arr_f32_new({out_f * in_f});")
        lines.append(f"    let b{idx}: i32 = arr_f32_new({out_f});")
    return lines


def gen_act_decls(arch):
    """One activation buffer per shape-changing step (input + each Linear's
    output).  Returns the source lines and the sizes list for downstream
    code that wants to know the activation widths."""
    if not arch or arch[0][0] != "linear":
        raise ValueError("arch must start with a Linear layer.")
    sizes = [arch[0][1]]
    for kind, *args in arch:
        if kind == "linear":
            sizes.append(args[1])
    lines = [f"    let a{i}: i32 = arr_f32_new({sz});"
             for i, sz in enumerate(sizes)]
    return lines, sizes


def gen_load(arch, embed_dir, out_name, embed):
    """Either runtime `file_read` calls (embed=False, single .f32 sidecar)
    or compile-time `embed_file` calls (embed=True, weights baked into the
    binary)."""
    if embed:
        lines = []
        for idx, in_f, out_f in linear_layers(arch):
            lines.append(f"    let W{idx}: i32 = embed_file(\"{embed_dir}/{out_name}_W{idx}.f32\");")
            lines.append(f"    let b{idx}: i32 = embed_file(\"{embed_dir}/{out_name}_b{idx}.f32\");")
        return lines
    lines = [f"    let weight_path: i32 = str_new(\"{out_name}.f32\");",
             "    let _wfd: i32 = file_open(weight_path, 0);"]
    for idx, in_f, out_f in linear_layers(arch):
        lines.append(f"    file_read(_wfd, W{idx}, {out_f * in_f * 4});")
        lines.append(f"    file_read(_wfd, b{idx}, {out_f * 4});")
    lines.append("    file_close(_wfd);")
    return lines


def gen_forward(arch):
    """Emit the per-sample forward pass on activation buffers a0..aN.

    cur_a tracks which activation buffer holds the running tensor.
    Linear creates a new shape ⇒ advance to the next buffer.  ReLU /
    sigmoid / tanh / softmax run in-place ⇒ keep the same buffer.
    """
    lines = []
    cur_a = 0
    li = 0
    for kind, *args in arch:
        if kind == "linear":
            in_f, out_f = args
            src = f"a{cur_a}"
            dst = f"a{cur_a + 1}"
            lines += emit_linear(li, in_f, out_f, src, dst, f"W{li}", f"b{li}")
            cur_a += 1
            li += 1
        elif kind == "relu":
            lines += emit_relu(f"a{cur_a}")
        elif kind == "sigmoid":
            lines += emit_sigmoid(f"a{cur_a}")
        elif kind == "tanh":
            lines += emit_tanh(f"a{cur_a}")
        elif kind == "softmax":
            lines += emit_softmax(f"a{cur_a}")
        else:
            raise ValueError(f"unknown layer kind: {kind!r}")
    return lines, cur_a


def gen_main(arch, args, out_name, embed_dir):
    weight_decls = gen_weight_decls(arch, args.embed)
    act_decls, _ = gen_act_decls(arch)
    load = gen_load(arch, embed_dir, out_name, args.embed)
    fwd, last = gen_forward(arch)

    n_in  = arch[0][1]
    n_out = next(i for i in reversed(arch) if i[0] == "linear")[2]

    body = []
    body.append(f"fn main() -> i32 {{")
    body += weight_decls
    body += load
    body += act_decls
    body.append("")

    if args.input_format == "stdin":
        # Single-shot CLI: read n_in raw bytes from stdin, run one forward
        # pass, print the predicted class to stdout.  No batch loop, no
        # external image files — the binary is fully self-contained.
        slots = (n_in + 7) // 8
        body.append(f"    let inbuf: i32 = arr_new({slots});")
        body.append(f"    file_read(0, inbuf, {n_in});")
        body.append("    let i: i32 = 0;")
        body.append(f"    while (i < {n_in}) {{")
        body.append("        let px: i32 = byte_at(inbuf, i);")
        body.append(f"        arr_f32_set(a0, i, (int_to_float(px) / 255.0 - {args.mean}) / {args.std});")
        body.append("        i = i + 1;")
        body.append("    }")
        body += [("    " + l.lstrip()) for l in fwd]
        if not args.no_argmax:
            body.append(f"    print_int(argmax_f32(a{last}, {n_out}));")
        else:
            body.append(f"    let i2: i32 = 0;")
            body.append(f"    while (i2 < {n_out}) {{")
            body.append(f"        print_f64(arr_f32_get(a{last}, i2), 6);")
            body.append("        i2 = i2 + 1;")
            body.append("    }")
        body.append("    return 0;")
        body.append("}")
        return "\n".join(body)

    # mnist mode: batch over the test set, report accuracy.
    if not args.input_images or not args.input_labels:
        raise SystemExit("--input-format mnist requires --input-images and --input-labels.")
    body.append(f"    let img_path: i32 = str_new(\"{args.input_images}\");")
    body.append(f"    let lbl_path: i32 = str_new(\"{args.input_labels}\");")
    body.append(f"    let imgs: i32 = load_byte_file(img_path, {args.n_test} * {n_in} + 16);")
    body.append(f"    let lbls: i32 = load_byte_file(lbl_path, {args.n_test} + 8);")
    body.append("")
    body.append(f"    print_str(\"aricode-pack inference, n={args.n_test}\");")
    body.append("    let correct: i32 = 0;")
    body.append("    let i: i32 = 0;")
    body.append(f"    while (i < {args.n_test}) {{")
    body.append(f"        load_image_at(imgs, 16 + i * {n_in}, a0);")
    body.append("        let lbl: i32 = byte_at(lbls, 8 + i);")
    body += [("        " + l.lstrip()) for l in fwd]
    if not args.no_argmax:
        body.append(f"        if (argmax_f32(a{last}, {n_out}) == lbl) {{ correct = correct + 1; }}")
    body.append("        i = i + 1;")
    body.append("    }")
    body.append("")
    body.append("    print_str(\"accuracy:\");")
    body.append(f"    print_f64(int_to_float(correct) / int_to_float({args.n_test}), 4);")
    body.append("    return 0;")
    body.append("}")
    return "\n".join(body)


# ──────────────────────────────────────────────────────────────────────
#  Top-level
# ──────────────────────────────────────────────────────────────────────


def parse_args():
    p = argparse.ArgumentParser(description="aricode-pack v0.1")
    p.add_argument("--checkpoint", required=True,
                   help="PyTorch state_dict .pt or .pth file (or a model "
                        "with .state_dict() attribute).")
    p.add_argument("--arch", required=True,
                   help="Architecture spec: JSON list of [kind, ...args].")
    p.add_argument("--keys", default="fc{idx_plus_1}.{kind}",
                   help="state_dict key template.  {idx} = layer index "
                        "(0-based), {idx_plus_1} = 1-based, {kind} = "
                        "weight|bias.  Default: fc{idx_plus_1}.{kind}.")
    p.add_argument("--input-format", choices=("mnist", "stdin"), default="mnist")
    p.add_argument("--input-images", default=None,
                   help="Path to raw MNIST images file (mnist mode only).")
    p.add_argument("--input-labels", default=None,
                   help="Path to raw MNIST labels file (mnist mode only).")
    p.add_argument("--n-test", type=int, default=10000,
                   help="Number of test samples to score in mnist mode.")
    p.add_argument("--mean", type=float, default=0.1307)
    p.add_argument("--std",  type=float, default=0.3081)
    p.add_argument("--no-argmax", action="store_true",
                   help="Skip argmax + accuracy reporting (e.g. when the "
                        "model isn't a classifier).")
    p.add_argument("--out", required=True,
                   help="Output base name.  <out>.ari is always written.  "
                        "Without --embed, a single <out>.f32 sidecar is "
                        "written too; with --embed, per-tensor "
                        "<out>_W{i}.f32 / <out>_b{i}.f32 staging files are "
                        "produced (the compiler bakes them into the binary "
                        "and they're no longer needed at runtime).")
    p.add_argument("--embed", action="store_true",
                   help="Emit a single self-contained binary: weights "
                        "embedded inline via embed_file, no runtime file "
                        "I/O for the model.  The MNIST images / labels "
                        "still come from disk.")
    return p.parse_args()


def expand_keys(template):
    """Adapt the template to a callable: keys(idx, kind)."""
    def keys(idx: int, kind: str):
        return template.format(idx=idx, idx_plus_1=idx + 1, kind=kind)
    return keys


def main():
    args = parse_args()

    if torch is None:
        print("error: PyTorch is required to read the checkpoint.", file=sys.stderr)
        sys.exit(2)

    arch = json.loads(Path(args.arch).read_text())
    if not isinstance(arch, list):
        raise SystemExit("--arch must contain a JSON list of [kind, ...args].")
    arch = [tuple(layer) for layer in arch]

    sd = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    if hasattr(sd, "state_dict"):
        sd = sd.state_dict()

    keys = expand_keys(args.keys)
    # Adapter to fit collect_weights' template-arg expectation.
    def keypat(idx, kind):
        return keys(idx, kind)

    # collect_weights expects a key template via .format with {idx, kind}
    # — simpler to pre-resolve to a dict.
    resolved = {}
    li = 0
    for kind, *largs in arch:
        if kind == "linear":
            resolved[("weight", li)] = keys(li, "weight")
            resolved[("bias",   li)] = keys(li, "bias")
            li += 1

    weights_blob = []
    li = 0
    for kind, *largs in arch:
        if kind == "linear":
            in_f, out_f = largs
            wkey = keys(li, "weight")
            bkey = keys(li, "bias")
            if wkey not in sd or bkey not in sd:
                raise SystemExit(
                    f"linear #{li}: missing '{wkey}' or '{bkey}' in checkpoint. "
                    f"Available keys: {sorted(sd.keys())}"
                )
            W = sd[wkey].detach().cpu().numpy().astype("float32")
            b = sd[bkey].detach().cpu().numpy().astype("float32")
            if W.shape != (out_f, in_f) or b.shape != (out_f,):
                raise SystemExit(
                    f"linear #{li}: shape mismatch.  expected ({out_f},{in_f}) "
                    f"+ ({out_f},); got {tuple(W.shape)} + {tuple(b.shape)}."
                )
            weights_blob.append(W)
            weights_blob.append(b)
            li += 1

    out_base = Path(args.out)
    src_path  = out_base.with_suffix(".ari")
    embed_dir = str(out_base.parent.resolve())

    if args.embed:
        # One .f32 per tensor, in W0/b0/W1/b1/... order.  embed_file
        # consumes them at compile time and bakes the bytes into the .text
        # section; they're not needed at runtime.
        wrote = []
        li = 0
        for kind, *largs in arch:
            if kind != "linear":
                continue
            W, b = weights_blob[2 * li], weights_blob[2 * li + 1]
            wp = out_base.parent / f"{out_base.name}_W{li}.f32"
            bp = out_base.parent / f"{out_base.name}_b{li}.f32"
            with open(wp, "wb") as f: W.tofile(f)
            with open(bp, "wb") as f: b.tofile(f)
            wrote.extend([wp, bp])
            li += 1
        print("wrote per-tensor staging files:")
        for p in wrote:
            print(f"  {p}")
    else:
        blob_path = out_base.with_suffix(".f32")
        with open(blob_path, "wb") as f:
            for arr in weights_blob:
                arr.tofile(f)
        print(f"wrote {blob_path}")

    src = (
        PROLOGUE.format(model_name=out_base.name,
                        arch_repr=arch,
                        loader=args.input_format)
        + "\n"
        + MNIST_LOADER.format(n_in=arch[0][1],
                              mean=args.mean,
                              std=args.std)
        + "\n"
        + gen_main(arch, args, out_base.name, embed_dir)
        + "\n"
    )
    src_path.write_text(src)

    n_floats = sum(a.size for a in weights_blob)
    print(f"wrote {src_path}  ({n_floats} f32 of weights total, {n_floats * 4} bytes)")
    print(f"build:  aric {src_path.name} -o {out_base.name}")
    if args.embed:
        print(f"        (after build, the per-tensor .f32 staging files can be deleted)")
    print(f"run:    ./{out_base.name}")


if __name__ == "__main__":
    main()
